### ISSUE TITLE
redcap_every_page_before_render crashes when called without a project_id in REDCap 8.0.3

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_chart_field#17]
It seems we have an incompatibility with older versions of REDCap.  The report below comes out of a REDCap 8.0.3 system. In addition to the content below, David reported that the problem does not occur on his REDCap 8.7.1 system running PHP 7.1.12. 

whereas we could raise or REDCap minimum version number to something we _know_ work, I think a better approach would be like David shows below that allows the code to work in REDCap 8.0.3. 

Here is David's somewhat paraphrased email:

> From: "Heskett, David" <davidheskett@wustl.edu>
> Subject: Module error message
> Date: August 21, 2018 at 8:18:20 AM CDT
> To: Philip B Chase <pbc@ufl.edu>
> 
> 
> PHP version on our servers is PHP 7.1
> REDCap version currently on our servers 8.0.3
> External Module:  REDCap Chart Field - v1.1.0
> 
> REDCap crashed due to an unexpected PHP fatal error!
> 
>     Error message: Uncaught ArgumentCountError: Too few arguments to function REDC
>     apChartField\ExternalModule\ExternalModule::redcap_every_page_before_render(),
>     0 passed and exactly 1 expected in /Users/davidheskett/wwwredcap8/modules/redc
>     ap_chart_field_v1.1.0/ExternalModule.php:32 Stack trace: #0 [internal
>     function]: REDCapChartField\ExternalModule\ExternalModule->redcap_every_page_b
>     efore_render() #1 /Users/davidheskett/wwwredcap8/redcap_v8.0.3/ExternalModules
>     /classes/ExternalModules.php(1161): call_user_func_array(Array, Array) #2 /Use
>     rs/davidheskett/wwwredcap8/redcap_v8.0.3/ExternalModules/classes/ExternalModul
>     es.php(1221): ExternalModules\ExternalModules::startHook('redcap_chart_fi...',
>     'v1.1.0', Array) #3
>     /Users/davidheskett/wwwredcap8/redcap_v8.0.3/Classes/Hooks.php(37):
>     ExternalModules\ExternalModules::callHook('every_page_befo...', Array) #4
>     /Users/davidheskett/wwwredcap8/redcap_v8.0.3/Classes/System.php(471):
>     Hooks::call('redcap_every_pa...') #5
>     /Users/davidheskett/wwwredcap8/redcap_v8.0.3/Config/init_global.php(9): Sy
> 
>     File: /Users/davidheskett/wwwredcap8/modules/redcap_chart_field_v1.1.0/ExternalModule.php
>     Line: 32
> 
> Changing this line
> 
>     function redcap_every_page_before_render($project_id) {
> 
> to 
> 
>     function redcap_every_page_before_render($project_id = 0) {
> 
> fixes the error.
> 
> You might consider doing this for detecting the project or system context
> 
>     if ($_GET['pid']) {
>      // project context
>     } else {
>      // system context
>     }
> 
> David Heskett
> Bus & Tech App Analyst II
> Informatics Core Services | Institute for Informatics
> Washington University School of Medicine
> davidheskett@wustl.edu

**Comment by tbembersimeao** [comment]
@pbchase #18 fixes it.
